module.exports = {
  directives: {
    defaultSrc: [
      "'self'",
      'http://*.bang-olufsen.com',
      'http://*.beoplay.com',
      'https://*.azure-api.net',
      'http://rum-collector-2.pingdom.net',
      'https://*.hotjar.com',
      'https://*.appspot.com',
      'http://*.google.com',
      'https://*.google.com',
      'https://*.googleapis.com',
    ],
    scriptSrc: [
      "'self'",
      "'unsafe-eval'",
      "'unsafe-inline'",
      'blob:',
      'tcLfmWTrWWgxBzcH9hSWXOOVThuDtAsGk3r',
      'https://cdn.polyfill.io',
      'https://cdnjs.cloudflare.com',
      'https://unpkg.com',
      'https://www.youtube.com',
      'http://*.bang-olufsen.com',
      'https://s.ytimg.com',
      'http://www.googleadservices.com',
      'http://bat.bing.com',
      'https://*.facebook.net',
      'https://www.google-analytics.com',
      'track.adform.net',
      'http://rum-static.pingdom.net',
      'http://*.sleeknote.com',
      'https://s.yimg.com/wi/ytc.js',
      'https://s.yimg.com',
      'https://secure.adnxs.com',
      'https://googleads.g.doubleclick.net',
      '*.hotjar.com',
      'http://*.yahoo.com',
      'https://*.yahoo.com',
      'https://*.arvato-payment.de',
      'https://*.googleapis.com',
      'http://www.googletagmanager.com',
      'https://www.googletagmanager.com',
      'http://*.google.com',
      'https://*.google.com',
    ],
    frameSrc: [
      'http://*.ctfassets.net',
      'https://*.hotjar.com',
      'https://*.doubleclick.net',
      'https://www.google.com',
      'https://www.google.co.in',
      'http://*.adform.net',
      'https://*.arvato-payment.de',
      'https://*.soundcloud.com',
      'https://www.youtube.com',
      'https://*.google.com',
    ],
    styleSrc: [
      "'self'",
      "'unsafe-inline'",
      'http://*.bang-olufsen.com',
      'http://www.googletagmanager.com',
      'https://www.googletagmanager.com',
      'https://*.google.com',
      'https://*.googleapis.com',
    ],
    imgSrc: [
      "'self'",
      'data:',
      'http://*.bang-olufsen.com',
      'http://*.beoplay.com',
      'http://*.ctfassets.net',
      'http://bat.bing.com',
      'https://www.google-analytics.com',
      'https://www.facebook.com',
      'https://secure.adnxs.com',
      'https://*.sleeknote.com',
      'https://www.google.com',
      'https://www.google.co.in',
      'https://*.doubleclick.net',
      'https://*.rackcdn.com',
      'https://*.youtube.com',
      'https://*.googleapis.com',
      'https://*.gstatic.com',
      'https://www.google.com.sg',
    ],
    mediaSrc: ['http://*.ctfassets.net'],
    fontSrc: [
      "'self'",
      'data:',
      'http://*.bang-olufsen.com',
      'http://*.beoplay.com',
      'https://*.googleapis.com',
      'https://*.gstatic.com',
    ],
    workerSrc: false,
  },
};
